//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chyba.
        /// </summary>
        internal static string Chyba {
            get {
                return ResourceManager.GetString("Chyba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plánovač++.
        /// </summary>
        internal static string HlavneOknoNazov {
            get {
                return ResourceManager.GetString("HlavneOknoNazov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nastala chyba.
        /// </summary>
        internal static string NastChyba {
            get {
                return ResourceManager.GetString("NastChyba", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov.
        /// </summary>
        internal static string Nazov {
            get {
                return ResourceManager.GetString("Nazov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkBtn {
            get {
                return ResourceManager.GetString("OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorita.
        /// </summary>
        internal static string Priorita {
            get {
                return ResourceManager.GetString("Priorita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vytvoriť udalosť.
        /// </summary>
        internal static string TlacVytvUdalost {
            get {
                return ResourceManager.GetString("TlacVytvUdalost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zmazať udalosť.
        /// </summary>
        internal static string TlacZmazUdalost {
            get {
                return ResourceManager.GetString("TlacZmazUdalost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treba vyplniť polia.
        /// </summary>
        internal static string TrebaVypPolia {
            get {
                return ResourceManager.GetString("TrebaVypPolia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        internal static string Udalost_cas_l {
            get {
                return ResourceManager.GetString("Udalost_cas_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miesto.
        /// </summary>
        internal static string Udalost_miesto_l {
            get {
                return ResourceManager.GetString("Udalost_miesto_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Názov.
        /// </summary>
        internal static string Udalost_nazov_l {
            get {
                return ResourceManager.GetString("Udalost_nazov_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popis udalosti.
        /// </summary>
        internal static string Udalost_popisUdalosti_l {
            get {
                return ResourceManager.GetString("Udalost_popisUdalosti_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priorita.
        /// </summary>
        internal static string Udalost_priorita_chb {
            get {
                return ResourceManager.GetString("Udalost_priorita_chb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulár Udalosť.
        /// </summary>
        internal static string UdalostOknoNazov {
            get {
                return ResourceManager.GetString("UdalostOknoNazov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Užívateľ.
        /// </summary>
        internal static string Uzivatel {
            get {
                return ResourceManager.GetString("Uzivatel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušiť.
        /// </summary>
        internal static string ZrusitBtn {
            get {
                return ResourceManager.GetString("ZrusitBtn", resourceCulture);
            }
        }
    }
}
